"""add description to products

Revision ID: 371e9d9555b9
Revises: 7257824c3492
Create Date: 2022-01-27 12:55:36.613998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371e9d9555b9'
down_revision = '7257824c3492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
